---
version: '3.8'

networks:
  traefik:
    external: true
  database:
    external: true

services:
  default:
    networks:
      - traefik
      - database
    image: registry.gitlab.com/demo/php-app/site-web:latest
    environment:
      APP_ENV: production
